# Generated by Django 4.1.5 on 2023-01-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='Japan', max_length=50),
            preserve_default=False,
        ),
    ]
